version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "node"
        versions: ["^15"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
