apiVersion: batch/v1
kind: CronJob
metadata:
  name: sciety--prod--data-pipeline
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
          - name: ship-events-to-s3
            image: amazon/aws-cli:2.4.23
            imagePullPolicy: IfNotPresent
            env: 
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: hive-prod-rds-postgres
                    key: postgresql-database
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: hive-prod-rds-postgres
                    key: postgresql-username
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: hive-prod-rds-postgres
                    key: postgresql-password
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: hive-prod-rds-postgres
                    key: postgresql-host
              - name: PGPORT
                valueFrom:
                  secretKeyRef:
                    name: hive-prod-rds-postgres
                    key: postgresql-port
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: sciety-events-shipper-aws-credentials
                    key: id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: sciety-events-shipper-aws-credentials
                    key: secret
            command:
            - /bin/bash 
            - -c
            - 'yum install --assumeyes --quiet postgresql && psql -A -t -c "select json_agg(events) from events;" > /data/events.json && aws s3 cp "/data/events.json" "s3://sciety-data-extractions/events-from-cronjob.json"'
            volumeMounts:
              - mountPath: /data
                name: data-volume
          containers:
          - name: bq-update-events
            image: google/cloud-sdk:422.0.0-slim
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash 
            - -c
            - 'apt install jq python3-venv && cat /data/events.json | jq -c ".[]" > /data/events.jsonl && python3 -m venv venv && venv/bin/pip install bigquery_schema_generator==1.5 && cat /data/events.jsonl | venv/bin/generate-schema > events.bq-schema.json '
            volumeMounts:
              - mountPath: /data
                name: data-volume
          volumes:
            - name: data-volume
              emptyDir: {} 
