version: '3.8'

services:
  app:
    container_name: sciety_app
    build:
      context: .
    environment:
      ALLOW_SITE_CRAWLERS: "true"
      APP_ORIGIN: "http://localhost:8080"
      APP_SECRET: "secret"
      APP_CACHE: '${APP_CACHE:-in-memory}'
      AUTHENTICATION_STRATEGY: '${AUTHENTICATION_STRATEGY:-twitter}'
      USE_STUB_ADAPTERS: '${USE_STUB_ADAPTERS:-false}'
      CROSSREF_API_BEARER_TOKEN:
      DISABLE_COOKIEBOT: '${DISABLE_COOKIEBOT}'
      EXPERIMENT_ENABLED: "true"
      FATHOM_SITE_ID:
      GOOGLE_TAG_MANAGER_ID:
      SCIETY_API: "http://app"
      SCIETY_TEAM_API_BEARER_TOKEN:
      INGEST_DEBUG:
      INGEST_ONLY:
      INGEST_DAYS:
      LOG_LEVEL:
      PGUSER: user
      PGHOST: db
      PGPASSWORD: secret
      PGDATABASE: sciety
      PRELIGHTS_FEED_KEY:
      TWITTER_API_KEY: '${TWITTER_API_KEY:-twitter-api-key}'
      TWITTER_API_SECRET_KEY: '${TWITTER_API_SECRET_KEY:-twitter-api-secret-key}'
      TWITTER_API_BEARER_TOKEN: '${TWITTER_API_BEARER_TOKEN:-twitter-api-bearer-token}'
      AUTH0_CLIENT_ID: '${AUTH0_CLIENT_ID:-auth0-client-id}'
      AUTH0_DOMAIN: 'dev-sqa2k3wwnhpxk36d.eu.auth0.com'
      AUTH0_CLIENT_SECRET: '${AUTH0_CLIENT_SECRET:-auth0-client-secret}'
      AUTH0_CALLBACK_URL: 'http://localhost:8080/auth0/callback'
    ports:
      - '8080:80'
    restart: unless-stopped

  db:
    container_name: sciety_db
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sciety
    volumes:
      - './data/backstop.csv:/data/backstop.csv'
      - './data/taiko.csv:/data/taiko.csv'
      - './data/exploratory-test.csv:/data/exploratory-test.csv'
      - './data/exploratory-test-from-prod.csv:/data/exploratory-test-from-prod.csv'
    healthcheck:
      test: pg_isready --username $$POSTGRES_USER --dbnam $$POSTGRES_DB || exit 1
      interval: 5s
  cache:
    container_name: sciety_cache
    image: redis:6.2-alpine
