version: '3.8'

services:
  app:
    container_name: sciety_app
    build:
      context: ""
    environment:
      ALLOW_SITE_CRAWLERS: "true"
      APP_ORIGIN: "http://localhost:8080"
      APP_SECRET: "secret"
      APP_CACHE: '${APP_CACHE:-in-memory}'
      AUTHENTICATION_STRATEGY: '${AUTHENTICATION_STRATEGY:-twitter}'
      AWS_ACCESS_KEY_ID: 'foo'
      AWS_SECRET_ACCESS_KEY: 'secret'
      AWS_DEFAULT_REGION: 'us-east-1'
      CROSSREF_API_BEARER_TOKEN:
      DISABLE_COOKIEBOT: '${DISABLE_COOKIEBOT}'
      EXPERIMENT_ENABLED: "true"
      FATHOM_SITE_ID:
      GOOGLE_TAG_MANAGER_ID:
      INGESTION_AUTH_BEARER_TOKEN:
      INGEST_DEBUG:
      INGEST_ONLY:
      INGEST_DAYS:
      LOG_LEVEL:
      PGUSER: user
      PGHOST: db
      PGPASSWORD: secret
      PGDATABASE: sciety
      PRELIGHTS_FEED_KEY:
      TWITTER_API_KEY: '${TWITTER_API_KEY:-twitter-api-key}'
      TWITTER_API_SECRET_KEY: '${TWITTER_API_SECRET_KEY:-twitter-api-secret-key}'
      TWITTER_API_BEARER_TOKEN: '${TWITTER_API_BEARER_TOKEN:-twitter-api-bearer-token}'
    ports:
      - '8080:80'
    restart: unless-stopped
  db:
    container_name: sciety_db
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sciety
    healthcheck:
      test: pg_isready --username $$POSTGRES_USER --dbnam $$POSTGRES_DB || exit 1
      interval: 5s
  cache:
    container_name: sciety_cache
    image: redis:6.2-alpine
  localstack:
    container_name: sciety_localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=us-east-1
      - 'SERVICES=sns,sqs'
      - DEBUG=0
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack-setup.sh:/docker-entrypoint-initaws.d/localstack-setup.sh"
