version: '3.8'

services:
  app:
    build:
      target: dev
    image: ${IMAGE}:${IMAGE_TAG}-dev
    volumes:
      - './.eslint:/app/.eslint'
      - './.gcp-ncrc-key.json:/var/run/secrets/app/.gcp-ncrc-key.json'
      - './.jest:/app/.jest'
      - './.stylelint:/app/.stylelint'
      - './build:/app/build'
      - './coverage:/app/coverage'
      - './data:/app/data'
      - './scripts:/app/scripts'
      - './src:/app/src'
      - './static:/app/static'
      - './test:/app/test'
      - './feature-test:/app/feature-test'

  lists:
    build:
      target: dev
    image: ${IMAGE}:${IMAGE_TAG}-dev
    command: "npx ts-node-dev --transpile-only src/lists-service/index"
    volumes:
      - './src:/app/src'
    
  events_publisher:
    build:
      target: dev
    image: ${IMAGE}:${IMAGE_TAG}-dev
    command: "npx ts-node-dev --transpile-only src/events-publisher"
    volumes:
      - './src:/app/src'
