version: '3.8'

services:
  app:
    build:
      target: dev
    image: ${IMAGE}:${IMAGE_TAG}-dev
    volumes:
      - './.eslint:/app/.eslint'
      - './.gcp-ncrc-key.json:/var/run/secrets/app/.gcp-ncrc-key.json'
      - './.jest:/app/.jest'
      - './.stylelint:/app/.stylelint'
      - './build:/app/build'
      - './coverage:/app/coverage'
      - './data:/app/data'
      - './scripts:/app/scripts'
      - './src:/app/src'
      - './reports:/app/reports'
      - './static:/app/static'
      - './test:/app/test'
      - './feature-test:/app/feature-test'

  lists:
    build:
      target: dev
    image: ${IMAGE}:${IMAGE_TAG}-dev
    volumes:
      - './src:/app/src'

  db:
    volumes:
      - './data/backstop.csv:/data/backstop.csv'
      - './data/taiko.csv:/data/taiko.csv'
      - './data/exploratory-test.csv:/data/exploratory-test.csv'
      - './data/exploratory-test-from-prod.csv:/data/exploratory-test-from-prod.csv'
