apiVersion: batch/v1
kind: Job
metadata:
  name: ingestion
spec:
  template:
    spec:
      containers:
      - name: app
        image: sciety/sciety:71965e116cf8a9cc70d7b2ad27c935c43cc40468
        command: ["node", "./build/ingest/update-event-data"]
      restartPolicy: Never
  backoffLimit: 4
