apiVersion: apps/v1
kind: Deployment
metadata:
  name: sciety--staging--cache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: "redis"
          # resources:
          #   requests:
          #     cpu: 1.0
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /ping
          #     port: http
          #   timeoutSeconds: 5
