apiVersion: v1
kind: Service
metadata:
  name: sciety--staging--cache 
  labels:
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - targetPort: redis
      port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/component: cache
