apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--cache
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  selector:
    matchLabels:
      {{- include "sciety.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "sciety.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: "redis"
          # resources:
          #   requests:
          #     cpu: 1.0
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /ping
          #     port: http
          #   timeoutSeconds: 5
