apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}--export-events
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: export-events
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccount: {{ .Release.Name }}--sciety-export-events
          containers:
            - name: ship-events-to-s3
              image: amazon/aws-cli:2.4.23
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - 'yum install --assumeyes --quiet postgresql && psql -A -t -c "COPY events TO STDOUT WITH (FORMAT CSV, HEADER);" > events.csv && aws s3 cp events.csv "s3://{{ .Values.exportBucketName }}/{{ .Release.Name }}--events-from-cronjob.csv"'
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}--public-env-vars
                - secretRef:
                    name: {{ .Release.Name }}--secret-env-vars

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}--sciety-export-events
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.eventShipperIAMRoleARN }}
