apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      {{- include "sciety.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "sciety.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          env:
            - name: ALLOW_SITE_CRAWLERS
              value: "{{ .Values.allowSiteCrawlers }}"
            - name: APP_ORIGIN
              value: https://{{ .Values.hostname }}
            - name: APP_SECRET
              value: "{{ .Values.appSecret }}"
            - name: CROSSREF_API_BEARER_TOKEN
              value: {{ .Values.crossrefApiBearerToken }}
            - name: EXPERIMENT_ENABLED
              value: "{{ .Values.experimentEnabled }}"
            - name: FATHOM_SITE_ID
              value: {{ .Values.fathomSiteId }}
            - name: GOOGLE_TAG_MANAGER_ID
              value: {{ .Values.googleTagManagerId }}
            - name: SCIETY_TEAM_API_BEARER_TOKEN
              value: {{ .Values.ingestionAuthBearerToken }}
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresqlSecretName }}"
                  key: postgresql-database
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresqlSecretName }}"
                  key: postgresql-username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresqlSecretName }}"
                  key: postgresql-password
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresqlSecretName }}"
                  key: postgresql-host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresqlSecretName }}"
                  key: postgresql-port
            - name: TWITTER_API_KEY
              value: {{ .Values.twitterApiKey }}
            - name: TWITTER_API_SECRET_KEY
              value: {{ .Values.twitterApiSecretKey }}
            - name: TWITTER_API_BEARER_TOKEN
              value: {{ .Values.twitterApiBearerToken }}
          volumeMounts:
            - name: gcp-ncrc-key
              mountPath: "/var/run/secrets/app"
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http
      volumes:
        - name: gcp-ncrc-key
          secret:
            secretName: ncrc-sheet-key
