apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}--ingestion
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  template:
    metadata:
      labels:
        {{- include "sciety.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ingestion
    spec:
      containers:
      - name: app
        image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
        env:
          - name: CROSSREF_API_BEARER_TOKEN
            value: {{ .Values.crossrefApiBearerToken }}
          - name: INGESTION_AUTH_BEARER_TOKEN
            value: {{ .Values.ingestionAuthBearerToken }}
        command: ["node", "./build/ingest/update-event-data"]
      restartPolicy: Never
  backoffLimit: 4
