apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}--ingestion
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "sciety.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: ingestion
        spec:
          containers:
          - name: app
            image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
            env:
              - name: CROSSREF_API_BEARER_TOKEN
                value: {{ .Values.crossrefApiBearerToken }}
              - name: INGESTION_AUTH_BEARER_TOKEN
                value: {{ .Values.ingestionAuthBearerToken }}
              - name: INGESTION_TARGET_APP
                value: "https://{{ .Values.hostname }}"
          restartPolicy: Never
