apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}--ingestion
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 720
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "sciety.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: ingestion
        spec:
          containers:
          - name: app
            image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
            command: ["sh", "-c", "node ./build/ingest/update-event-data && wget --quiet https://hc-ping.com/{{ .Values.healthchecksPingKey }}/{{ .Release.Name | replace '--' '-' }}"]
            env:
              - name: CROSSREF_API_BEARER_TOKEN
                value: {{ .Values.crossrefApiBearerToken }}
              - name: SCIETY_TEAM_API_BEARER_TOKEN
                value: {{ .Values.ingestionAuthBearerToken }}
              - name: INGESTION_TARGET_APP
                value: "https://{{ .Values.hostname }}"
              - name: PRELIGHTS_FEED_KEY
                value: {{ .Values.prelightsFeedKey }}
            volumeMounts:
              - name: gcp-ncrc-key
                mountPath: "/var/run/secrets/app"
                readOnly: true
          volumes:
            - name: gcp-ncrc-key
              secret:
                secretName: ncrc-sheet-key
          restartPolicy: Never
