apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--lists-read-model
  labels:
    {{- include "sciety.labels" . | nindent 4 }}
    app.kubernetes.io/component: lists-read-model
spec:
  type: ClusterIP
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
  selector:
    {{- include "sciety.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lists-read-model
