images:
  frontend:
    repository: ghcr.io/sciety/sciety

allowSiteCrawlers: "false"
crossrefApiBearerToken:
experimentEnabled: "false"
coarNotificationDeliveryEnabled: "false"
fathomSiteId: 
googleTagManagerId:
appSecret: "not-a-secret-coming-from-helm-chart-defaults"
ingestionAuthBearerToken:
healthchecksPingKey:
enableEventsExportToS3: "true"
certManagerClusterIssuer: "letsencrypt"
